const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.Platform,
		C3.Behaviors.Flash,
		C3.Plugins.TiledBg,
		C3.Plugins.Keyboard,
		C3.Behaviors.destroy,
		C3.Plugins.Text,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.EightDir.Acts.Stop,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar
	];
};
self.C3_JsPropNameTable = [
	{"8Direcciones": 0},
	{Plataforma: 0},
	{Parpadeo: 0},
	{CondorVolando: 0},
	{FondoEnMosaico: 0},
	{Teclado: 0},
	{DestruirFuera: 0},
	{Montaña: 0},
	{YInicial: 0},
	{Piedra: 0},
	{Parajo: 0},
	{CartelPerdiste: 0},
	{Tiempo: 0},
	{CuadroTiempo: 0},
	{BotonPausa: 0},
	{ControlTáctil: 0},
	{BotonSubir: 0},
	{BotonBajar: 0},
	{Mouse: 0},
	{Audio: 0},
	{FondoEnMosaico2: 0},
	{Tweeninterpolación: 0},
	{Titulo: 0},
	{Seno: 0},
	{BotonComenzar: 0},
	{CondorMenu: 0},
	{Fade: 0},
	{valleviejocidudad: 0},
	{secretarialogo: 0},
	{susanalogo: 0},
	{FondoEnMosaico3: 0},
	{Sprite: 0},
	{estadoCondor: 0},
	{CondorSaltando: 0},
	{Recolectada: 0},
	{Moneda: 0},
	{Sprite2: 0},
	{MonedasTexto: 0},
	{Sprite3: 0},
	{TextoVidas: 0},
	{TiempoRestante: 0},
	{GameOver: 0},
	{Monedas: 0},
	{AlturaMonedas: 0},
	{Vidas: 0}
];

self.InstanceType = {
	CondorVolando: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	Montaña: class extends self.ISpriteInstance {},
	Piedra: class extends self.ISpriteInstance {},
	Parajo: class extends self.ISpriteInstance {},
	CartelPerdiste: class extends self.ISpriteInstance {},
	Tiempo: class extends self.ITextInstance {},
	CuadroTiempo: class extends self.ISpriteInstance {},
	BotonPausa: class extends self.ISpriteInstance {},
	ControlTáctil: class extends self.IInstance {},
	BotonSubir: class extends self.ISpriteInstance {},
	BotonBajar: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	Titulo: class extends self.ISpriteInstance {},
	BotonComenzar: class extends self.ISpriteInstance {},
	CondorMenu: class extends self.ISpriteInstance {},
	Fade: class extends self.ISpriteInstance {},
	valleviejocidudad: class extends self.ISpriteInstance {},
	secretarialogo: class extends self.ISpriteInstance {},
	susanalogo: class extends self.ISpriteInstance {},
	FondoEnMosaico3: class extends self.ITiledBackgroundInstance {},
	Sprite: class extends self.ISpriteInstance {},
	CondorSaltando: class extends self.ISpriteInstance {},
	Moneda: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	MonedasTexto: class extends self.ITextInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	TextoVidas: class extends self.ITextInstance {}
}